mariadb:
  environment:
    MYSQL_ROOT_PASSWORD: "${mysql_root_password}"
    MYSQL_DATABASE: "${mysql_database}"
    MYSQL_USER: "${mysql_user}"
    MYSQL_PASSWORD: "${mysql_password}"
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: ${host_label}
    io.rancher.container.pull_image: always
  tty: true
  image: mariadb
  volumes:
  - /home/donnuadmin/isdpa/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  stdin_open: true
drupal:
  ports:
  - 10771:80/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_soft: ${host_label}
    io.rancher.container.hostname_override: container_name
  tty: true
  image: soundman/data:isdpa070316v1
  links:
  - mariadb: '${mysql_allias_name}'
  stdin_open: true